M48
; DRILL file {KiCad 7.0.8} date Sun Jan  7 20:15:48 2024
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-01-07T20:15:48-08:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X3.0268Y-3.7644
X3.0268Y-3.9553
T2
X2.9075Y-3.7526
X2.9075Y-3.9671
T0
M30
